# Generated by Django 3.0.2 on 2020-02-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
