# Generated by Django 3.0.2 on 2020-02-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200204_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_file',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
