# Generated by Django 3.0.2 on 2020-02-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200205_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbnail_file',
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(null=True),
        ),
    ]
